### ISSUE TITLE
Syntax error in Js function 

### ISSUE THREAD

**Issue by imVinayPandya** [chris-held/elixirforajsdev#4]
I love you guys, what you are doing. I recently watch your video on Youtube about "Learn Elixir for Js Developers" and I saw one small syntax error.

In basic section of your https://elixirforajs.dev/ there is one section called "Function", where you have written 

`const add(n1, n2) => n1 + n2;`

but correct syntax is like

`const add = (n1, n2) => n1 + n2;`

**Comment by chris-held** [comment]
Thanks for catching that @imVinayPandya!

**Comment by imVinayPandya** [comment]
Happy to help..... keep doing good work. I am also wanted to contribute in this project, let me know if I can help you.
